# Generated by Django 2.2.6 on 2019-11-09 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calcutron', '0002_parent_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
