# Generated by Django 3.1.1 on 2022-12-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcutron', '0004_set_sort_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='long_text',
        ),
    ]
