# Generated by Django 3.1.1 on 2020-09-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcutron', '0004_set_sort_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Task'), ('note', 'Note')], default='task', max_length=255),
        ),
    ]
