# Generated by Django 3.1.1 on 2022-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcutron', '0005_combine_task_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(),
        ),
    ]
