# Generated by Django 6.0.1 on 2026-02-11 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_top_level_parents(apps, schema_editor):
    Task = apps.get_model("calcutron", "Task")

    all_tasks = Task.objects.all()
    
    for task in all_tasks:
        if task.parent is None:
            continue

        top_level_parent = task.parent
        while top_level_parent.parent is not None:
            top_level_parent = top_level_parent.parent

        task.top_level_parent = top_level_parent
        task.save()
        task.users.set([])


def set_users(apps, schema_editor):
    Task = apps.get_model("calcutron", "Task")

    all_tasks = Task.objects.all()
    
    for task in all_tasks:
        task.users.set(task.top_level_parent.users.all())


class Migration(migrations.Migration):

    dependencies = [
        ('calcutron', '0007_alter_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='top_level_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_descendants', to='calcutron.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_top_level_parents, set_users),
    ]
