# Generated by Django 6.0.2 on 2026-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcutron', '0008_task_top_level_parent_alter_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
